config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  get 'home/index'  

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: {:new => '' }
  resources :articles do
    resources :comments, only: :create
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
   validates :title, presence: true
   validates :text, presence: true
   has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author, presence: true
  validates :body, presence: true
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

private
  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :username
  end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!, :only => [:new, :create] 

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.order "created_at DESC"
  end

  def new
  end

  def create
    #render plain: params[:article].inspect
     @article = Article.new(article_params) 
     if @article.save      
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy 
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end


  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authenticate_user!, :only => [:create] 
  
  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    
  end

  def create        
    @contact = Contact.new(contact_params)  
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.html.erb
<h1>Article created!</h1>
<%= link_to 'Show all articles', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit article!</h1>


	<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<% if @article && @article.errors.any? %>
	<p>	
		<ul>
		<% @article.errors.full_messages.each do |msg|  %>
			<li> <%= msg %></li>
		<% end %>
		</ul>
	</p>
	<% end %>
	<p>
		<%= f.label :title %> <br/>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :text %> <br/>
		<%= f.text_area :text %>
	</p>
	<p>
		<%= f.submit %> <br/>	
	</p>
	<% end %>

app/views/articles/index.html.erb
<h1>Main page</h1>
<% @articles.each do |article| %>
	<h3>
		<%= link_to article.title, article_path(article) %>
	</h3>
	<p>
		<%= article.text %>
	</p>
	<p>
		Created at <%= article.created_at %> by <%=  %>
	</p>
	<p>
		<%= link_to 'Show', article_path(article) %> 
		<% if user_signed_in? %>
		| 	<%= link_to 'Edit', edit_article_path(article) %> | 
		<%= link_to 'Destroy', article_path(article), method: :delete, data: {confirm: 'Do you really want to destroy it?'} %>
		<% end %>
	</p>
	<hr/>
<% end %>

app/views/articles/new.html.erb
<h1>New article!</h1>

<%= form_for :article, url: articles_path do |f| %>
<% if @article && @article.errors.any? %>
<p>	
	<ul>
	<% @article.errors.full_messages.each do |msg|  %>
		<li> <%= msg %></li>
	<% end %>
	</ul>
</p>
<% end %>
<p>
	<%= f.label :title %> <br/>
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :text %> <br/>
	<%= f.text_area :text %>
</p>
<p>
	<%= f.submit 'Post article', :class => 'btn btn-primary' %>
</p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
<%= @article.text %>
</p>
<%= link_to 'Show all articles', articles_path %>
<hr/>
<h2>Comments:</h2>
<% @article.comments.each do |comment| %>
	<p>
		<%= comment.body %>
	</p>
	<p>
		<span style="color: #999; font-size:75%">Written by <%= comment.author %> at <%= comment.created_at %></span>
	</p>
	<hr/>
<% end %>

<% if user_signed_in? %>
<p>
	Your comment:
<%= form_for([@article, @article.comments.build]) do |f| %>
	<% if @article && @article.errors.any? %>
	<p>	
		<ul>
		<% @article.errors.full_messages.each do |msg|  %>
			<li> <%= msg %></li>
		<% end %>
		</ul>
	</p>
	<% end %>
	<p>
		<%= f.label :author %> <br/>
		<%= f.text_field :author, :value => current_user.username %>
	</p>
	<p>
		<%= f.label :body %> <br/>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit 'Post comment', :class => 'btn btn-primary' %>
		<br/>	
	</p>
<% end %>
</p>
<% else %>
<p>
You should be logged in to comment.
</p>
<% end %>

app/views/contacts/create.html.erb
<h1>Thanks!</h1>

app/views/contacts/new.html.erb
<h1>Contact us</h1>

<%= form_for :contact, url: contacts_path do |f| %>
<% if @contact && @contact.errors.any? %>
<p>	
	<ul>
	<% @contact.errors.full_messages.each do |msg|  %>
		<li> <%= msg %></li>
	<% end %>
	</ul>
</p>
<% end %>
<p>
	<%= f.label :email %> <br/>
	<%= f.text_field :email %>
</p>
<p>
	<%= f.label :message %> <br/>
	<%= f.text_area :message %>
</p>
<p>
	<%= f.submit 'Send message' %> <br/>	
</p>
<% end %>

app/views/home/index.html.erb
<h1>Welcome!</h1>
<p>We are glad to see you.</p>

app/views/layouts/application.html.erb
	<!DOCTYPE html>
	<html>
	<head>
	  <title>MyLittleBlog</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <script data-require="jquery@*" data-semver="2.1.4" src="https://code.jquery.com/jquery-2.1.4.js"></script>
	  <script data-require="bootstrap@*" data-semver="3.3.6" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	  <link data-require="bootstrap-css@3.3.6" data-semver="3.3.6" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" />
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
		<!-- Static navbar -->
			<nav class="navbar navbar-default" role="navigation">
			  <div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			      <span class="sr-only">Toggle navigation</span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    <a class="navbar-brand" href="/">Blog RoR</a>
			  </div>
			  <div class="navbar-collapse collapse">
			    <ul class="nav navbar-nav">
			      <li><a href="<%= articles_path %>">Articles</a></li>
			      <li><a href="<%= new_article_path %>">New</a></li>			      		      
			    </ul>			    
				  <ul class="nav navbar-nav navbar-right">
				  	<li>
				  		<% if user_signed_in? %>
				  			<li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %> </li>
				  		<% else %>
				  			<li><%= link_to 'Sign in', new_user_session_path %> </li>
				  		<% end %>				  		
				  	</li>			    		
			      </ul>
			  </div>
			  
			  <!--/.nav-collapse -->
			</nav>
			<div class="row">
				<div class="col-xs-12">
					<% if user_signed_in? %>
						Hello, <%= current_user.username %>
					<% end %>

					  <p class="notice"><%= notice %></p>
					  <p class="alert"><%= alert %></p>

					<%= yield %>
				</div>
				
			</div>
		</div>
	</body>
	</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>
	We are cool!
</p>

app/views/pages/terms.html.erb
<h1>Terms of service</h1>